CREATE TABLE "sites" (
  "site_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "site_name" varchar(100) NOT NULL,
  "city" varchar(50),
  "address" varchar(200),
  "latitude" decimal(10,6),
  "longitude" decimal(10,6),
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "device_types" (
  "device_type_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "type_name" varchar(50) UNIQUE NOT NULL,
  "category" varchar(30)
);

CREATE TABLE "devices" (
  "device_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "device_name" varchar(100) NOT NULL,
  "serial_number" varchar(50) UNIQUE NOT NULL,
  "ip_address" inet UNIQUE,
  "site_id" int,
  "device_type_id" int,
  "status" varchar(20) NOT NULL DEFAULT 'active',
  "installed_date" date,
  "last_seen" timestamp,
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "device_connections" (
  "connection_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "source_device_id" int,
  "target_device_id" int,
  "connection_type" varchar(30),
  "bandwidth_mbps" int
);

CREATE TABLE "metric_thresholds" (
  "threshold_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "metric_type" varchar(50) UNIQUE NOT NULL,
  "warning_value" decimal(10,2) NOT NULL,
  "critical_value" decimal(10,2) NOT NULL,
  "unit" varchar(20) NOT NULL
);

CREATE TABLE "metrics" (
  "metric_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "device_id" int,
  "threshold_id" int,
  "metric_value" decimal(10,2) NOT NULL,
  "collected_at" timestamp DEFAULT (now())
);

CREATE TABLE "alerts" (
  "alert_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "device_id" int,
  "threshold_id" int,
  "severity" varchar(20) NOT NULL,
  "message" text,
  "triggered_at" timestamp DEFAULT (now()),
  "resolved_at" timestamp,
  "status_id" int
);

CREATE TABLE "alert_statuses" (
  "status_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "status_name" varchar(30) UNIQUE NOT NULL
);

CREATE TABLE "engineers" (
  "engineer_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "first_name" varchar(50) NOT NULL,
  "last_name" varchar(50) NOT NULL,
  "email" varchar(100) UNIQUE,
  "phone" varchar(20),
  "role" varchar(50),
  "hire_date" date
);

CREATE TABLE "engineer_assignments" (
  "assignment_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "engineer_id" int,
  "device_id" int,
  "assigned_at" timestamp DEFAULT (now())
);

CREATE TABLE "maintenance_tasks" (
  "task_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "device_id" int,
  "engineer_id" int,
  "alert_id" int,
  "task_type" varchar(50),
  "description" text,
  "scheduled_date" date,
  "completed_date" date,
  "status" varchar(20) DEFAULT 'PENDING'
);

CREATE TABLE "alert_history" (
  "history_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "alert_id" int,
  "old_status_id" int,
  "new_status_id" int,
  "changed_by" int,
  "changed_at" timestamp DEFAULT (now())
);

ALTER TABLE "devices" ADD FOREIGN KEY ("site_id") REFERENCES "sites" ("site_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "devices" ADD FOREIGN KEY ("device_type_id") REFERENCES "device_types" ("device_type_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "device_connections" ADD FOREIGN KEY ("source_device_id") REFERENCES "devices" ("device_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "device_connections" ADD FOREIGN KEY ("target_device_id") REFERENCES "devices" ("device_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "metrics" ADD FOREIGN KEY ("device_id") REFERENCES "devices" ("device_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "metrics" ADD FOREIGN KEY ("threshold_id") REFERENCES "metric_thresholds" ("threshold_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "alerts" ADD FOREIGN KEY ("device_id") REFERENCES "devices" ("device_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "alerts" ADD FOREIGN KEY ("threshold_id") REFERENCES "metric_thresholds" ("threshold_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "alerts" ADD FOREIGN KEY ("status_id") REFERENCES "alert_statuses" ("status_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "engineer_assignments" ADD FOREIGN KEY ("engineer_id") REFERENCES "engineers" ("engineer_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "engineer_assignments" ADD FOREIGN KEY ("device_id") REFERENCES "devices" ("device_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "maintenance_tasks" ADD FOREIGN KEY ("device_id") REFERENCES "devices" ("device_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "maintenance_tasks" ADD FOREIGN KEY ("engineer_id") REFERENCES "engineers" ("engineer_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "maintenance_tasks" ADD FOREIGN KEY ("alert_id") REFERENCES "alerts" ("alert_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "alert_history" ADD FOREIGN KEY ("alert_id") REFERENCES "alerts" ("alert_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "alert_history" ADD FOREIGN KEY ("old_status_id") REFERENCES "alert_statuses" ("status_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "alert_history" ADD FOREIGN KEY ("new_status_id") REFERENCES "alert_statuses" ("status_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "alert_history" ADD FOREIGN KEY ("changed_by") REFERENCES "engineers" ("engineer_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "devices" ALTER COLUMN "site_id" SET NOT NULL;
ALTER TABLE "devices" ALTER COLUMN "device_type_id" SET NOT NULL;
ALTER TABLE "device_connections" ALTER COLUMN "source_device_id" SET NOT NULL;
ALTER TABLE "device_connections" ALTER COLUMN "target_device_id" SET NOT NULL;
ALTER TABLE "metrics" ALTER COLUMN "device_id" SET NOT NULL;
ALTER TABLE "metrics" ALTER COLUMN "threshold_id" SET NOT NULL;
ALTER TABLE "alerts" ALTER COLUMN "device_id" SET NOT NULL;
ALTER TABLE "alerts" ALTER COLUMN "threshold_id" SET NOT NULL;
ALTER TABLE "alerts" ALTER COLUMN "status_id" SET NOT NULL;
ALTER TABLE "engineer_assignments" ALTER COLUMN "engineer_id" SET NOT NULL;
ALTER TABLE "engineer_assignments" ALTER COLUMN "device_id" SET NOT NULL;
ALTER TABLE "maintenance_tasks" ALTER COLUMN "device_id" SET NOT NULL;
ALTER TABLE "maintenance_tasks" ALTER COLUMN "engineer_id" SET NOT NULL;
ALTER TABLE "alert_history" ALTER COLUMN "alert_id" SET NOT NULL;
ALTER TABLE "alert_history" ALTER COLUMN "old_status_id" SET NOT NULL;
ALTER TABLE "alert_history" ALTER COLUMN "new_status_id" SET NOT NULL;
ALTER TABLE "alert_history" ALTER COLUMN "changed_by" SET NOT NULL;

ALTER TABLE "devices" ADD CONSTRAINT chk_devices_status 
    CHECK (status IN ('active', 'maintenance', 'decommissioned'));

ALTER TABLE "device_connections" ADD CONSTRAINT chk_connection_type 
    CHECK (connection_type IN ('ETHERNET', 'FIBER', 'WIRELESS'));

ALTER TABLE "device_connections" ADD CONSTRAINT chk_bandwidth 
    CHECK (bandwidth_mbps > 0);

ALTER TABLE "metric_thresholds" ADD CONSTRAINT chk_threshold_values 
    CHECK (warning_value > 0 AND critical_value > 0 AND critical_value > warning_value);

ALTER TABLE "metrics" ADD CONSTRAINT chk_metric_value 
    CHECK (metric_value >= 0);

ALTER TABLE "alerts" ADD CONSTRAINT chk_severity 
    CHECK (severity IN ('INFO', 'WARNING', 'CRITICAL'));

ALTER TABLE "engineers" ADD CONSTRAINT chk_engineer_role 
    CHECK (role IN ('NETWORK_ENGINEER', 'NOC_OPERATOR', 'SUPPORT'));

ALTER TABLE "maintenance_tasks" ADD CONSTRAINT chk_maintenance_type 
    CHECK (task_type IN ('PREVENTIVE', 'CORRECTIVE', 'UPGRADE'));

ALTER TABLE "maintenance_tasks" ADD CONSTRAINT chk_maintenance_status 
    CHECK (status IN ('PENDING', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED'));

CREATE INDEX idx_devices_site_id ON devices(site_id);
CREATE INDEX idx_devices_device_type_id ON devices(device_type_id);
CREATE INDEX idx_metrics_device_id ON metrics(device_id);
CREATE INDEX idx_metrics_collected_at ON metrics(collected_at);
CREATE INDEX idx_alerts_device_id ON alerts(device_id);
CREATE INDEX idx_alerts_status_id ON alerts(status_id);
CREATE INDEX idx_alerts_triggered_at ON alerts(triggered_at);
CREATE INDEX idx_maintenance_tasks_device_id ON maintenance_tasks(device_id);
CREATE INDEX idx_maintenance_tasks_engineer_id ON maintenance_tasks(engineer_id);